<a href="https://colab.research.google.com/github/Ritvik10/Data-Science-Overview-Material-Practice-and-Revision/blob/main/Day_23_Searching%2C_Sorting%2C_Stacking_and_String_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import scipy as sp
from scipy import stats

In [2]:
arr = np.array([1,2,3,4,5,6,7,98,102,2])

In [5]:
# Mean -> sum(elements) / len(elements)
"""
Age
34
23
65
Mean(x)
45
21
"""

'\nAge\n34\n23\n65\nMean(x)\n45\n21\n'

In [6]:
arr

array([  1,   2,   3,   4,   5,   6,   7,  98, 102,   2])

In [7]:
arr.ndim

1

In [8]:
arr.shape

(10,)

In [9]:
row(10), column

NameError: ignored

In [10]:
np.mean(arr)

23.0

In [11]:
arr1 = [1,2,3,4,5,6,7]

In [12]:
np.mean(arr1)

4.0

In [13]:
arr2 = [1,2,3,4,5,6,7,200]

In [14]:
np.mean(arr2)

28.5

In [15]:
# Median
arr = np.array([1,2,3,4,5,6,7,98,102,2])

In [16]:
arr

array([  1,   2,   3,   4,   5,   6,   7,  98, 102,   2])

In [17]:
1,2,2,3,4,5,6,7,98,102

(1, 2, 2, 3, 4, 5, 6, 7, 98, 102)

In [19]:
#(4 + 5) / 2 = 9/2 = 4.5

In [20]:
np.median(arr)

4.5

In [21]:
arr1 = np.array([1,2,3,4,5,6,7,98,102])

In [22]:
np.median(arr1)

5.0

In [23]:
arr2 = [1,2,3,4,5,6,7,200]

In [24]:
np.mean(arr2)

28.5

In [25]:
np.median(arr2)

4.5

In [26]:
# Mode
arr = [1,2,1,2,1,2,2,3,4,3,4,5]

In [27]:
stats.mode(arr)

<ipython-input-27-d8a1cfb848a5>:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(arr)


ModeResult(mode=array([2]), count=array([4]))

In [28]:
# Standard Deviation
arr

[1, 2, 1, 2, 1, 2, 2, 3, 4, 3, 4, 5]

In [29]:
np.std(arr)

1.2583057392117916

In [32]:
import math

In [33]:
SD = sqrt(var)

NameError: ignored

In [34]:
# Variance
np.var(arr)

1.5833333333333333

# Flatten

In [35]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [36]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Sorting

In [38]:
arr = np.array([[67, 34, 12, 9],
                [8, 45, 67, 99],
                [102, 155, 17, 84]])

In [39]:
arr

array([[ 67,  34,  12,   9],
       [  8,  45,  67,  99],
       [102, 155,  17,  84]])

In [40]:
# Ascending Order
np.sort(arr)

array([[  9,  12,  34,  67],
       [  8,  45,  67,  99],
       [ 17,  84, 102, 155]])

In [41]:
np.sort(arr, axis=1)

array([[  9,  12,  34,  67],
       [  8,  45,  67,  99],
       [ 17,  84, 102, 155]])

In [42]:
np.sort(arr, axis=0)

array([[  8,  34,  12,   9],
       [ 67,  45,  17,  84],
       [102, 155,  67,  99]])

In [43]:
arr

array([[ 67,  34,  12,   9],
       [  8,  45,  67,  99],
       [102, 155,  17,  84]])

In [44]:
np.sort(arr, axis=-1)

array([[  9,  12,  34,  67],
       [  8,  45,  67,  99],
       [ 17,  84, 102, 155]])

In [45]:
# Descending Order
-np.sort(-arr)

array([[ 67,  34,  12,   9],
       [ 99,  67,  45,   8],
       [155, 102,  84,  17]])

In [46]:
-np.sort(-arr, axis=1)

array([[ 67,  34,  12,   9],
       [ 99,  67,  45,   8],
       [155, 102,  84,  17]])

In [47]:
-np.sort(-arr, axis=0)

array([[102, 155,  67,  99],
       [ 67,  45,  17,  84],
       [  8,  34,  12,   9]])

# Stacking

In [48]:
arr1 = [1,2,3,4]
arr2 = [5,6,7,8]

In [49]:
arr1

[1, 2, 3, 4]

In [50]:
arr2

[5, 6, 7, 8]

In [51]:
np.hstack((arr1, arr2)) # Horizontal Stacking

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
np.vstack((arr1, arr2)) # Vertical Stacking

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
np.dstack((arr1, arr2)) # Depth Stacking

array([[[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]])

# Searching

In [54]:
arr

array([[ 67,  34,  12,   9],
       [  8,  45,  67,  99],
       [102, 155,  17,  84]])

In [55]:
# where() -> returns the indices of elements w.r.t. the given condition
# extract() -> returns the elements w.r.t. the given condition

In [56]:
np.where(arr==9)

(array([0]), array([3]))

In [57]:
arr[0,3]

9

In [58]:
np.extract(arr>100, arr)

array([102, 155])

# String Functions/Operations

In [59]:
# Concatenation

In [60]:
a = ['Hello']
b = [' World']

In [61]:
"Hello" + "World"

'HelloWorld'

In [62]:
a

['Hello']

In [63]:
b

[' World']

In [64]:
np.char.add(a,b)

array(['Hello World'], dtype='<U11')

In [65]:
a = ["Hello", "Goodbye", "Good Night"]
b = [" World", " Good Morning", " Guten Morgan"]

In [66]:
a

['Hello', 'Goodbye', 'Good Night']

In [67]:
b

[' World', ' Good Morning', ' Guten Morgan']

In [68]:
np.char.add(a,b)

array(['Hello World', 'Goodbye Good Morning', 'Good Night Guten Morgan'],
      dtype='<U23')

In [69]:
# Multiply
"Hello" * 3

'HelloHelloHello'

In [70]:
np.char.multiply("Hello", 3)

array('HelloHelloHello', dtype='<U15')

In [71]:
# Capitalize
np.char.capitalize("hello world")

array('Hello world', dtype='<U11')

In [72]:
# Upper
np.char.upper("hello, good evening and good morning")

array('HELLO, GOOD EVENING AND GOOD MORNING', dtype='<U36')

In [73]:
# Lower
np.char.lower("HELLO, GOOD EVENING AND GOOD MORNING")

array('hello, good evening and good morning', dtype='<U36')

In [74]:
# Split
np.char.split('Moneyhellodoeshellobuyhellohappiness', 'hello')

array(list(['Money', 'does', 'buy', 'happiness']), dtype=object)

In [75]:
# Title
np.char.title('hello how are you')

array('Hello How Are You', dtype='<U17')

In [76]:
# Splitlines
np.char.splitlines("Prints the values to a stream, or to sys.stdout by default.\nOptional keyword arguments:\nfile:  a file-like object (stream); defaults to the current sys.stdout.\nsep:   string inserted between values, default a space.\nend:   string appended after the last value, default a newline.\nflush: whether to forcibly flush the stream.")

array(list(['Prints the values to a stream, or to sys.stdout by default.', 'Optional keyword arguments:', 'file:  a file-like object (stream); defaults to the current sys.stdout.', 'sep:   string inserted between values, default a space.', 'end:   string appended after the last value, default a newline.', 'flush: whether to forcibly flush the stream.']),
      dtype=object)

In [77]:
print.__doc__

"print(value, ..., sep=' ', end='\\n', file=sys.stdout, flush=False)\n\nPrints the values to a stream, or to sys.stdout by default.\nOptional keyword arguments:\nfile:  a file-like object (stream); defaults to the current sys.stdout.\nsep:   string inserted between values, default a space.\nend:   string appended after the last value, default a newline.\nflush: whether to forcibly flush the stream."

* Homework: https://www.math-exercises.com/matrices/matrix-equations