<a href="https://colab.research.google.com/github/Ritvik10/Data-Science-Overview-Material-Practice-and-Revision/blob/main/Day_24_Introduction_to_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([[45,23,98],[56,2,1],[4,67,34]])

In [3]:
arr

array([[45, 23, 98],
       [56,  2,  1],
       [ 4, 67, 34]])

In [4]:
np.sort(arr)

array([[23, 45, 98],
       [ 1,  2, 56],
       [ 4, 34, 67]])

In [5]:
np.sort(arr, axis=0)

array([[ 4,  2,  1],
       [45, 23, 34],
       [56, 67, 98]])

# Pandas

1. Python's Library
2. It is use to work with datasets
3. Functions

* Analyze
* Clean
* Explore
* Visualize
* Manipulate

# Why Pandas?

1. It is fast
2. It can be use to analyze Big Datas
3. It is use to clean messy data and then make it readable and relevant

# Importation of Pandas

In [6]:
import pandas as pd

In [7]:
pd.__version__

'1.5.3'

In [8]:
!pip install pandas

# Series

* It is a 1D array like Data Structure
* [1,2,3,4,5,6]
* Series is Imumtable
* The data in a series is mutable

* C -> Creation

In [9]:
# SYNTAX
pd.Series(data, index, dtype)

NameError: ignored

* Creating an empty Series

In [10]:
s = pd.Series()

<ipython-input-10-399a7d257b44>:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s = pd.Series()


In [11]:
s

Series([], dtype: float64)

In [13]:
"""64GB
128GB
256GB"""

'64GB\n128GB\n256GB'

In [14]:
#23GB

In [15]:
"""1GB = 1024 MB
1MB = 1024 Bytes
1 Byte = 8bit"""

'1GB = 1024 MB\n1MB = 1024 Bytes\n1 Byte = 8bit'

In [16]:
8, 16,32, 64

(8, 16, 32, 64)

In [17]:
type(s)

pandas.core.series.Series

* Creating a Series using NumPy array

In [18]:
data = np.array([12.4, 45, 32, 89])
s = pd.Series(data)

In [19]:
s

0    12.4
1    45.0
2    32.0
3    89.0
dtype: float64

In [20]:
data = np.array([12.4, 45, 32, 89])
s = pd.Series(data, index=[101, 102, 103, 104])
s

101    12.4
102    45.0
103    32.0
104    89.0
dtype: float64

In [21]:
data = np.array([12.4, 45, 32, 89])
s = pd.Series(data, index=[101, 102, 103])
s

ValueError: ignored


* Creating a Series using Dictionary

In [22]:
data = {"a": 10, "b":40, "c":90, "d":95}
s = pd.Series(data)
s

a    10
b    40
c    90
d    95
dtype: int64

In [23]:
data = {"a": 10, "b":40, "c":90, "d":95}
s = pd.Series(data, index = ['c', 'a', 'b', 'd'])
s

c    90
a    10
b    40
d    95
dtype: int64

In [24]:
data = {"a": 10, "b":40, "c":90, "d":95}
s = pd.Series(data, index = ['c', 'a', 'b', 'd'], dtype='int8')
s

c    90
a    10
b    40
d    95
dtype: int8

In [26]:
#NaN -> Not a Number

* Creating a Series using a Scalar Value

In [27]:
data = 99
s = pd.Series(data, index=[201, 202, 203, 204, 205])
s

201    99
202    99
203    99
204    99
205    99
dtype: int64

* U -> Updation

* Accessing the data from the Pandas Series DS

In [28]:
data = [12, 45, 32, 89, -7, -10, 21, -0.5, -7, 30]
s = pd.Series(data)
s

0    12.0
1    45.0
2    32.0
3    89.0
4    -7.0
5   -10.0
6    21.0
7    -0.5
8    -7.0
9    30.0
dtype: float64

In [29]:
s[4]

-7.0

In [30]:
s[:3]

0    12.0
1    45.0
2    32.0
dtype: float64

In [31]:
s[4:7]

4    -7.0
5   -10.0
6    21.0
dtype: float64

In [32]:
s

0    12.0
1    45.0
2    32.0
3    89.0
4    -7.0
5   -10.0
6    21.0
7    -0.5
8    -7.0
9    30.0
dtype: float64

In [33]:
s[-3:]

7    -0.5
8    -7.0
9    30.0
dtype: float64

In [34]:
data = {"a": 10, "b":40, "c":90, "d":95}
s = pd.Series(data, index = ['c', 'a', 'b', 'd', 'e'])
s

c    90.0
a    10.0
b    40.0
d    95.0
e     NaN
dtype: float64

In [35]:
s[['c', 'd']]

c    90.0
d    95.0
dtype: float64

In [36]:
s['c':'a']

c    90.0
a    10.0
dtype: float64

In [37]:
s

c    90.0
a    10.0
b    40.0
d    95.0
e     NaN
dtype: float64

In [38]:
s['a'] = 110

In [39]:
s

c     90.0
a    110.0
b     40.0
d     95.0
e      NaN
dtype: float64

In [40]:
s["c": "d"] = 56

In [41]:
s

c    56.0
a    56.0
b    56.0
d    56.0
e     NaN
dtype: float64

In [42]:
s["c": "d"] = [76, 76, 76, 54]

In [43]:
s

c    76.0
a    76.0
b    76.0
d    54.0
e     NaN
dtype: float64

* Boolean Masking

In [44]:
data = {"a": 10, "b":40, "c":90, "d":95}
s = pd.Series(data, index = ['c', 'a', 'b', 'd'])
s

c    90
a    10
b    40
d    95
dtype: int64

In [45]:
s[s>50]

c    90
d    95
dtype: int64

In [46]:
s[s>30][s<50]

b    40
dtype: int64

In [47]:
s[s.between(10,50, inclusive=False)]

<ipython-input-47-20f303e31246>:1: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  s[s.between(10,50, inclusive=False)]


b    40
dtype: int64

* NumPy Functions

In [48]:
s

c    90
a    10
b    40
d    95
dtype: int64

In [49]:
s.shape

(4,)

In [50]:
s.ndim

1

In [51]:
s.size

4

In [52]:
s.index

Index(['c', 'a', 'b', 'd'], dtype='object')

In [53]:
s.values

array([90, 10, 40, 95])

In [54]:
s

c    90
a    10
b    40
d    95
dtype: int64

In [55]:
10 in s

False

In [56]:
'a' in s

True

* Deletion

In [57]:
s

c    90
a    10
b    40
d    95
dtype: int64

In [58]:
s.drop(['b', 'd'], inplace=True)
# dropna() -> DataFrame

In [59]:
s

c    90
a    10
dtype: int64

In [60]:
s+10

c    100
a     20
dtype: int64

In [61]:
s

c    90
a    10
dtype: int64

In [62]:
s-10

c    80
a     0
dtype: int64

In [63]:
s * 10

c    900
a    100
dtype: int64

In [64]:
s / 10

c    9.0
a    1.0
dtype: float64

In [65]:
s ** 2

c    8100
a     100
dtype: int64

In [66]:
np.power(s,2)

c    8100
a     100
dtype: int64

In [67]:
np.exp(s)

c    1.220403e+39
a    2.202647e+04
dtype: float64

In [68]:
s

c    90
a    10
dtype: int64

In [69]:
s['c'] = s['c'] - 10

In [70]:
s

c    80
a    10
dtype: int64

In [71]:
s['e'] = s['c'] + 20

In [72]:
s

c     80
a     10
e    100
dtype: int64

In [73]:
len(s)

3

In [74]:
s.drop('e') # Single Element
s.drop(['e', 'b']) # Multiple Element

KeyError: ignored