<a href="https://colab.research.google.com/github/Ritvik10/Data-Science-Overview-Material-Practice-and-Revision/blob/main/Day_22_NumPy_CRUD_%26_Mathematical_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create

In [2]:
arr = np.array([[1,2,3],[4]])

<ipython-input-2-15b504824958>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[1,2,3],[4]])


In [3]:
arr

array([list([1, 2, 3]), list([4])], dtype=object)

In [4]:
arr.ndim

1

In [5]:
arr1 = np.array([[1,2,3],[4,5,6,7]])

<ipython-input-5-e6ea96434888>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1 = np.array([[1,2,3],[4,5,6,7]])


In [6]:
arr1.ndim

1

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [8]:
arr2.ndim

2

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

* empty()

In [10]:
np.empty([3,4])

array([[1.1776272e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [11]:
np.empty([3,4]).ndim

2

In [12]:
np.empty([3,4]).shape

(3, 4)

* zeros()

In [13]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

* ones()

In [14]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#Q -> 5 X 5 -> All the outer elements will be 1 and inner elements will be zero

In [16]:
one = np.ones((5,5))


In [17]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
one[1:-1,1:-1] = 0

In [19]:
one

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
one_1 = np.ones((5,5))
zero_1 = np.zeros((3,3))

In [21]:
one_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
zero_1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
one_1[1:4, 1:4] = zero_1

In [24]:
one_1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

* full()

In [25]:
np.full((3,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

* Identity matrix -> eye()

Square Matrix -> No. of rows = No. of Columns = n

In [26]:
"""
n X n
2 X 2
3 X 3
"""

'\nn X n\n2 X 2\n3 X 3\n'

In [27]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

* identity()

In [28]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

* diag()

In [29]:
np.diag([10,20,30,40])

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

* linspace()

In [30]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [31]:
0.52631579 * 2

1.05263158

# Update

In [32]:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]])

In [33]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [34]:
arr[1,2:4]

array([8, 9])

In [35]:
arr[1:3, 2:4]

array([[ 8,  9],
       [13, 14]])

* append()

In [36]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [37]:
# np.append(array, value(s), axis)

In [38]:
np.append(arr,[[10, 20, 30, 40, 50]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 10, 20,
       30, 40, 50])

In [39]:
np.append(arr,[[10, 20, 30, 40, 50]], axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [10, 20, 30, 40, 50]])

In [40]:
np.append(arr,[[10], [20], [30]], axis=1)

array([[ 1,  2,  3,  4,  5, 10],
       [ 6,  7,  8,  9, 10, 20],
       [11, 12, 13, 14, 15, 30]])

# Deletion

In [43]:
# List
"""
pop
remove
del
"""

'\npop\nremove\ndel\n'

* np.delete()

In [44]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [45]:
arr[1,3] = 2

In [46]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  2, 10],
       [11, 12, 13, 14, 15]])

In [47]:
# SYNTAX -> np.delete(array, index, axis(0->Row, 1->Column))

In [48]:
np.delete(arr, 2, 1)

array([[ 1,  2,  4,  5],
       [ 6,  7,  2, 10],
       [11, 12, 14, 15]])

# Mathematical Operations

In [49]:
arr1 = np.ones((2,2))
arr2 = np.zeros((2,2))

In [50]:
arr1

array([[1., 1.],
       [1., 1.]])

In [51]:
arr2

array([[0., 0.],
       [0., 0.]])

In [52]:
arr3 = np.full((2,3), 5)

In [53]:
arr3

array([[5, 5, 5],
       [5, 5, 5]])

In [54]:
# Addition of two metrices
arr1 + arr2

array([[1., 1.],
       [1., 1.]])

In [55]:
arr1 + arr3

ValueError: ignored

In [57]:
# Subtraction of two metrices

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[6,5,4],[3,2,1]])

In [58]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr2

array([[6, 5, 4],
       [3, 2, 1]])

In [60]:
arr1 - arr2

array([[-5, -3, -1],
       [ 1,  3,  5]])

In [61]:
# Division of two metrices

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,20,30],[40,50,60]])

In [62]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr2

array([[10, 20, 30],
       [40, 50, 60]])

In [64]:
arr2 / arr1

array([[10., 10., 10.],
       [10., 10., 10.]])

In [65]:
arr2 / 5

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [66]:
# Multiplication of two metrices

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[6,5,4],[3,2,1]])

In [67]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr2

array([[6, 5, 4],
       [3, 2, 1]])

In [69]:
arr1 * arr2

array([[ 6, 10, 12],
       [12, 10,  6]])

In [70]:
# Dot Product -> dot() & matmul()

arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([[7,8],
                 [9,10],
                 [11,12]])

In [71]:
arr3 = np.array([[3,4,5],
                [6,7,8]])

In [72]:
arr3.shape

(2, 3)

In [73]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
arr2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [75]:
arr1.shape

(2, 3)

In [76]:
arr2.shape

(3, 2)

In [77]:
np.dot(arr1,arr2)

array([[ 58,  64],
       [139, 154]])

In [78]:
np.matmul(arr1, arr2)

array([[ 58,  64],
       [139, 154]])

In [79]:
np.dot(arr1,arr3)

ValueError: ignored

In [80]:
np.matmul(arr1,arr3)

ValueError: ignored

In [81]:
# Cross Product -> cross()

In [82]:
A = np.array([1,2])
B = np.array([-4,2])

In [83]:
np.cross(A,B)

array(10)

# Detrminant of a Matrix

In [84]:
# np.linalg.det

In [85]:
arr = np.array([[1,2],
                [3,4]])

In [86]:
np.linalg.det(arr)

-2.0000000000000004

# Statistics

In [87]:
arr = np.array([[11, 67, 34],
                [98, 56, 54],
                [9, 23, 101]])

In [88]:
arr

array([[ 11,  67,  34],
       [ 98,  56,  54],
       [  9,  23, 101]])

In [89]:
# np.max(array, axis)

In [90]:
np.max(arr, axis=1)

array([ 67,  98, 101])

In [91]:
np.max(arr, axis=0)

array([ 98,  67, 101])

In [92]:
np.max(arr)

101

In [93]:
max(arr)

ValueError: ignored

In [94]:
arr

array([[ 11,  67,  34],
       [ 98,  56,  54],
       [  9,  23, 101]])

In [95]:
# np.min()

In [96]:
np.min(arr)

9

In [97]:
np.min(arr, axis=1)

array([11, 54,  9])

In [98]:
np.min(arr, axis=0)

array([ 9, 23, 34])

In [99]:
# np.sum()

In [100]:
np.sum(arr)

453

In [101]:
np.sum(arr, axis=1)

array([112, 208, 133])

In [102]:
np.sum(arr, axis=0)

array([118, 146, 189])

In [103]:
# Inverse of a Matrix
arr

array([[ 11,  67,  34],
       [ 98,  56,  54],
       [  9,  23, 101]])

In [104]:
np.linalg.inv(arr)

array([[-0.00844704,  0.01145345, -0.00328007],
       [ 0.01801167, -0.00154052, -0.00523969],
       [-0.00334896, -0.00066979,  0.01138647]])

In [105]:
arr

array([[ 11,  67,  34],
       [ 98,  56,  54],
       [  9,  23, 101]])

In [106]:
# Transpose of a Matrix
arr.T

array([[ 11,  98,   9],
       [ 67,  56,  23],
       [ 34,  54, 101]])

In [107]:
arr.transpose()

array([[ 11,  98,   9],
       [ 67,  56,  23],
       [ 34,  54, 101]])

In [108]:
arr

array([[ 11,  67,  34],
       [ 98,  56,  54],
       [  9,  23, 101]])

In [109]:
arr = np.array([[11, 67, 34],
                [98, 56, 54],
                [9, 23, 101]], dtype='float')

In [110]:
arr

array([[ 11.,  67.,  34.],
       [ 98.,  56.,  54.],
       [  9.,  23., 101.]])

In [111]:
# Reciprocal
np.reciprocal(arr)

array([[0.09090909, 0.01492537, 0.02941176],
       [0.01020408, 0.01785714, 0.01851852],
       [0.11111111, 0.04347826, 0.00990099]])

In [112]:
np.reciprocal(arr)

array([[0.09090909, 0.01492537, 0.02941176],
       [0.01020408, 0.01785714, 0.01851852],
       [0.11111111, 0.04347826, 0.00990099]])

In [113]:
# floor() & ceil()

In [114]:
arr

array([[ 11.,  67.,  34.],
       [ 98.,  56.,  54.],
       [  9.,  23., 101.]])

In [115]:
arr = np.array([[11.78, 67.23, 34.89],
                [98.33, 56.32, 54.45],
                [9.23, 23.45, 101.99]], dtype='float')

In [116]:
arr

array([[ 11.78,  67.23,  34.89],
       [ 98.33,  56.32,  54.45],
       [  9.23,  23.45, 101.99]])

In [117]:
np.floor(arr)

array([[ 11.,  67.,  34.],
       [ 98.,  56.,  54.],
       [  9.,  23., 101.]])

In [118]:
np.ceil(arr)

array([[ 12.,  68.,  35.],
       [ 99.,  57.,  55.],
       [ 10.,  24., 102.]])

In [119]:
# LCM

3 6 12 24 36

SyntaxError: ignored

In [120]:
np.lcm.reduce((3,6,12,24,36))

72

In [121]:
# GCD
np.gcd.reduce((3,9,12))

3

In [123]:
# Linear Eq.
"""
3x + y = 9
x  + 2y = 8

x = ?
y = ?
"""

'\n3x + y = 9\nx  + 2y = 8\n\nx = ?\ny = ?\n'

In [124]:
left = np.array([[3,1],
                 [1,2]])

right = np.array([9,8])

In [125]:
np.linalg.solve(left, right)

array([2., 3.])

In [126]:
# np.sqrt()