<a href="https://colab.research.google.com/github/Ritvik10/Data-Science-Overview-Material-Practice-and-Revision/blob/main/Day_21_Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

* It stands for Numerical Python
* It is a Python library for working with arrays
* It also has functions that helps to work on some domains such as Linear Algebra, Metrics, Fourier Theorem, etc.

# Why NumPy

* It is 50x faster than list
* It consumes less memory
* The NumPy array is known as ndarray

# Demo to show that how the NumPy is faster than List

In [1]:
# pip install numpy -> Local (PyCharm, VSCode)
!pip install numpy -> Notebooks (Jupyter, Google Colab)

/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `pip install numpy -> Notebooks (Jupyter, Google Colab)'


In [2]:
import numpy as np
import time

In [3]:
elements = np.random.rand(100000000)

In [4]:
elements

array([0.04496598, 0.99991867, 0.26783263, ..., 0.2589319 , 0.94323999,
       0.11135898])

In [5]:
len(elements)

100000000

In [6]:
# NumPY
start = time.time()
mean_np = np.mean(elements)
print(time.time() - start)

0.09391450881958008


In [7]:
# List
start = time.time()
mean_li = sum(elements) / len(elements)
print(time.time() - start)

10.787930965423584


In [8]:
mean_np

0.5000165280643037

In [9]:
mean_li

0.500016528064199

# Check the NumPy version

In [12]:
#np.__version__ -> Google Colab
# numpy --version -> Local

# Initializing the NumPy array

In [13]:
# Zeroth Dimension -> 0D

arr = np.array(1)
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
arr.ndim

0

In [15]:
arr

array(1)

In [16]:
# One Dimension -> 1D

arr_one = np.array([1,2,3,4,5,6])
print(type(arr_one))
print(arr_one)
print(arr_one.ndim)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]
1


In [17]:
# Two Dimension -> 2D

arr_two = np.array(
                    [
                      [1,2,3,4],
                      [5,6,7,8]
                     ]
                   )
print(type(arr_two))
print(arr_two)
print(arr_two.ndim)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
2


In [18]:
# Three Dimension -> 3D

arr_three = np.array(
                    [[
                      [1,2,3,4],
                      [5,6,7,8]
                     ],
                   [
                      [1,2,3,4],
                      [5,6,7,8]
                     ]]
                   )
print(type(arr_three))
print(arr_three)
print(arr_three.ndim)

<class 'numpy.ndarray'>
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
3


# Check the dimension

In [19]:
arr.ndim

0

In [20]:
arr_one.ndim

1

In [21]:
arr_two.ndim

2

In [22]:
arr_three.ndim

3

# Making a ndarray to n-dimensional array

In [23]:
one_arr = np.array([1,2,3,4,5])
one_arr.ndim

1

In [24]:
one_arr = np.array([1,2,3,4,5], ndmin=10)
print(one_arr)
one_arr.ndim

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]


10

In [25]:
one_arr = np.array([1,2,3,4,5], ndmin=31)
print(one_arr)
one_arr.ndim

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4 5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


31

In [26]:
two_arr = np.array([[1,2,3,4],
                    [5,6,7,8]], ndmin=3)
print(two_arr)
two_arr.ndim

[[[1 2 3 4]
  [5 6 7 8]]]


3

# No. of rows X No. of Columns

In [27]:
b = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])

In [28]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
b.shape

(2, 5)

In [30]:
one = np.array([1,2,3,4])

In [31]:
one.shape

(4,)

In [32]:
(2,3)
(4,)

(4,)

# Size -> To count the number of elements

In [33]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
b.size

10

In [35]:
len(b)

2

# Accessing the elements

In [36]:
# 1D
arr_one = np.array([1,2,3,4,5])
arr_one

array([1, 2, 3, 4, 5])

In [37]:
arr_one[:]

array([1, 2, 3, 4, 5])

In [38]:
arr_one[3]

4

In [39]:
# 2D
arr_two = np.array([[1,2,3,4],
                    [5,6,7,8]])
arr_two

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
arr_two[1,2]

7

In [41]:
arr_two[1,2] = 70

In [42]:
arr_two

array([[ 1,  2,  3,  4],
       [ 5,  6, 70,  8]])

In [43]:
arr_two[0,0:3]

array([1, 2, 3])

In [44]:
arr_two[0,0:3] = [10, 20, 30]

In [45]:
arr_two

array([[10, 20, 30,  4],
       [ 5,  6, 70,  8]])

In [46]:
arr_two[0,0:3] = 23

In [47]:
arr_two

array([[23, 23, 23,  4],
       [ 5,  6, 70,  8]])

In [48]:
arr_two[0:4]

array([[23, 23, 23,  4],
       [ 5,  6, 70,  8]])

# Operations

In [49]:
arr_two

array([[23, 23, 23,  4],
       [ 5,  6, 70,  8]])

In [50]:
arr_two + 10

array([[33, 33, 33, 14],
       [15, 16, 80, 18]])

In [51]:
arr_two - 10

array([[13, 13, 13, -6],
       [-5, -4, 60, -2]])

In [52]:
arr_two * 10

array([[230, 230, 230,  40],
       [ 50,  60, 700,  80]])

In [53]:
arr_two / 10

array([[2.3, 2.3, 2.3, 0.4],
       [0.5, 0.6, 7. , 0.8]])

In [54]:
[1,2,3,4,5] + 10

TypeError: ignored

In [55]:
np.array([1,2,3,4,5]) + 10

array([11, 12, 13, 14, 15])

# Copy Vs View

In [56]:
arr_two

array([[23, 23, 23,  4],
       [ 5,  6, 70,  8]])

In [57]:
# Copy
copy_fun = arr_two.copy()

In [58]:
copy_fun += 100

In [59]:
copy_fun

array([[123, 123, 123, 104],
       [105, 106, 170, 108]])

In [60]:
arr_two

array([[23, 23, 23,  4],
       [ 5,  6, 70,  8]])

In [61]:
# View
view_fun = arr_two.view()

In [62]:
view_fun += 100

In [63]:
view_fun

array([[123, 123, 123, 104],
       [105, 106, 170, 108]])

In [64]:
arr_two

array([[123, 123, 123, 104],
       [105, 106, 170, 108]])

# Reshape

In [65]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [66]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
a.shape

(12,)

In [69]:
#(2,6)(6,2)(4,3)(3,4)(1,12)(12,1) -> 2D
#(1,2,6)(1,6,2)(2,6,1)(6,2,1)(1,4,3)()

In [70]:
a.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [71]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [72]:
a.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [73]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [74]:
a.reshape(-1,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [75]:
a.reshape(-1,5)

ValueError: ignored

# Iterate

In [76]:
a = np.array([1,2,3,4,5,6])

In [77]:
for i in a:
  print(i)

1
2
3
4
5
6


In [78]:
a_2 = np.array([[1,2,3,4,5,6],
                [7,8,9,10,11,12]])

In [79]:
for i in a_2:
  for j in i:
    print(j)

1
2
3
4
5
6
7
8
9
10
11
12


In [80]:
for i in np.nditer(a_2):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [81]:
a_2.dtype

dtype('int64')

# Task 5

* https://colab.research.google.com/drive/1iVw8dEYI883E-Q8Qd4Th9-jeum-Aa2TE?usp=sharing

* https://colab.research.google.com/drive/1amBpsmUeVu-71Oi1Lnvyd986IrF6o48j?usp=sharing

* https://colab.research.google.com/drive/1lWS1UXQCntu_HWNNBHbzojE6mVR6x4iJ?usp=sharing

* https://colab.research.google.com/drive/1CS85AaHrNxTabO5_b_ICaDEiYaYyeWV_?usp=sharing

* https://colab.research.google.com/drive/1gHLSDVEGAHuSBbf2U98Adqj1gXro-dEy?usp=sharing

* https://colab.research.google.com/drive/1PXMDTFoJvkhNi5lr-wUhjwSxSgVGr2Ls?usp=sharing

* https://colab.research.google.com/drive/1ANh-NZb6hnrJnpR2KN9VPCGdGezkihkM?usp=sharing

* https://colab.research.google.com/drive/1Fp_erNhIXremdlXyqHWmKhCYPrmmqWAE?usp=sharing

* https://colab.research.google.com/drive/1OQfyH1oL0Mdfl3OR7ky0m4HUKOApyCJI?usp=sharing

* https://colab.research.google.com/drive/1iVw8dEYI883E-Q8Qd4Th9-jeum-Aa2TE?usp=sharing

* https://colab.research.google.com/drive/1QoMWXOdwL2Vbw81bCsclNthUxVZWlTG_#scrollTo=iXpAefN46lOk

* https://colab.research.google.com/drive/1Jnk56M9o_Qz4Qo1FgxSCK7ppf59VaZTR?usp=sharing

* https://colab.research.google.com/drive/1nP0JYswlp3QmzT1hZyA1N-PmswMChMV_?usp=sharing
